<center><font color='steelblue'> <font size = "5,5">CORPORACIÓN UNIVERSITARIA MINUTO DE DIOS </font></center><br>
<center><font color='steelblue'> <font size = "5">FACULTAD DE INGENIERÍA</font></center><br>
<center><font color='steelblue'> <font size = "4">PROGRAMA INGENIERÍA DE SISTEMAS</font></center><br>
<center><font color='steelblue'> <font size = "3">CURSO BASES DE DATOS MASIVAS</font></center><br>
<center><font color="yellow" size = "4" face = "small fonts">Talle PYTHON</font></center>

<center><font color="olive" size = "4" face = "small fonts">DATOS DE LOS PARTICIPANTES DEL GRUPO</font></center>

<font color="yellow" size = "4" face = "small fonts">NRC: </font></center><br>
<font color="yellow" size = "4" face = "small fonts">Nombre: </font></center><br>
<font color="yellow" size = "4" face = "small fonts">ID: </font></center><br>

<font color="yellow" size = "4" face = "small fonts">El taller retoma algunas de las instrucciones utilizadas a través del curso de Bases de Datos Masivas, tener en cuenta seguir los pasos requeridos.</font></center><br>

<font color="yellow" size = "4" face = "small fonts">Al Cargar los archivos dispuestos en la carpeta TERCERPARCIAL se debe utilizar sentencias que no fijen el path, este debe se dinámico en caso de que se creen nuevos paquetes</font></center><br>
.

<font color="red" size = "4" face = "small fonts">El ejercicio consta de seguir el cuaderno y  realizar las tareas solicitadas, Utilizar y citar la documentación propia de cada una de las herramientas utilizadas para realizar el tratamiento a la data.</font></center><br>

<font color="red" size = "4" face = "small fonts">Calificación del siguiente bloque 1/5</font></center><br>

<font color="yellow" size = "4" face = "small fonts">1. Configuración e importe de las librerias de pandas y propias.</font></center><br>

In [1]:

#Utilizar las buenas practicas de python
import os
import sys
import io
import json
import requests
import pandas as pd
import numpy as np

sys.path.append(os.path.abspath(os.path.join('..')))
from functions.misfunciones import unir_excel_en_csv,alterar_columnas,establecer_conexion

<font color="yellow" size = "4" face = "small fonts">2. Leer un archivo.CSV e imprimirlo desde la carpeta data</font></center><br>

In [2]:
#Utilizar las buenas practicas de python
csv_path = os.path.join(os.getcwd(), ".." , "data" , "data.csv")

file = pd.read_csv(csv_path, encoding='latin1',low_memory=False)
file.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

<font color="yellow" size = "4" face = "small fonts">3. Leer un archivo.HTML que contenga data e imprimirlo desde un sitio WEB</font></center><br>

In [3]:
#Utilizar las buenas practicas de python

headers = {"User-Agent":"Mozilla/5.0"}
url = "https://en.wikipedia.org/wiki/Demographics_of_Russia"

response = requests.get(url,headers=headers)

russian_population = pd.read_html(io.StringIO(response.text), match="Vital Statistics of Russia as of 1946")[0]

russian_population.head()

  Unnamed: 0_level_0 Total average population (1 January 1993 onwards)  \
  Unnamed: 0_level_1 Total average population (1 January 1993 onwards)
0               1946                                          98028000
1               1947                                          98834000
2               1948                                          99706000
3               1949                                         101160000
4               1950                                         102833000

  Live births     Deaths Natural change Crude birth rate (per 1,000)  \
  Live births     Deaths Natural change Crude birth rate (per 1,000)
0     2546000  1210000.0      1336000.0                         26.0
1     2715000  1680000.0      1035000.0                         27.5
2     2516000  1310000.0      1206000.0                         25.2
3     3089000  1187000.0      1902000.0                         30.5
4     2859000  1180000.0      1679000.0                         27.8

  Crude death rate (per 1,000) Natural change (per 1,000)  \
  Crude death rate (per 1,000) Natural change (per 1,000)
0                         12.3                       13.6
1                         17.0                       10.5
2                         13.1                       12.1
3                         11.7                       18.8
4                         11.5                       16.3

  Crude migration change (per 1,000) Total fertility rate[fn 2] Fertility  \
  Crude migration change (per 1,000) Total fertility rate[fn 2]     urban
0                               -5.4                       2.81       NaN
1                               -1.7                       2.94       NaN
2                                2.5                       2.60       NaN
3                               -2.3                       3.21       NaN
4                               -0.7                       2.89       NaN

        Life Expectancy               \
  rural            male female total
0   NaN            46.6   55.3   NaN
1   NaN            39.9   49.8   NaN
2   NaN            47.0   56.0   NaN
3   NaN            51.0   59.8   NaN
4   NaN            52.3   61.0   NaN

  Abortions reported (including miscarriages)
  Abortions reported (including miscarriages)
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN

<font color="yellow" size = "4" face = "small fonts">4. Leer un archivo.XLSX que contenga data e imprimirlo desde el modulo /data</font></center><br>

In [4]:
#Utilizar las buenas practicas de python
excel_path = os.path.join(os.getcwd(),"..","data","RELAX1.XLSX")

excel = pd.read_excel(excel_path)
excel.head(10)

,Mat.gestion.stock,Material,Texto breve de material,TpMt,UMB,Mat,SM,Grupo art.,Jquía.productos,NºFb,Fabricante,Grupo artíc. ext.,Creado,Últ.mod.
0,71000000091,91000000001,"WIRE, NONELECTRICAL",HERS,M,NaN,NaN,261215,NaN,10011477,CENTELSA,NaN,2016-04-27,2022-10-03
1,71000000091,91000000002,"WIRE, NONELECTRICAL",HERS,M,NaN,NaN,261215,NaN,200303,CENTELSA,NaN,2016-04-27,2022-10-03
2,71000000091,91000000003,"WIRE, NONELECTRICAL",HERS,M,X,NaN,261215,NaN,200354,CENTELSA,NaN,2016-04-27,2022-10-03
3,71000000125,91000000004,"WIRE, NONELECTRICAL",HERS,M,NaN,NaN,261215,NaN,2051016R - NEGRO,CENTELSA,NaN,2016-04-27,2022-10-03
4,71000000158,91000252927,"CABLE ASSEMBLY, POWER, ELECTRICAL",HERS,M,NaN,NaN,261216,NaN,C THHN/THWN 90°C CU 2 AWG 600,CENTELSA,NaN,2016-04-27,2022-10-03
5,71000000182,91000000006,"CABLE ASSEMBLY, POWER, ELECTRICAL",HERS,M,NaN,NaN,261216,NaN,4 CAUCA,CEAT-GEN,NaN,2016-04-27,2022-10-03
6,71000000182,91000000007,"CABLE ASSEMBLY, POWER, ELECTRICAL",HERS,M,NaN,NaN,261216,NaN,CABLE 4AWG-THW,CEAT-GEN,NaN,2016-04-27,2022-10-03
7,71000000182,91000000008,"CABLE ASSEMBLY, POWER, ELECTRICAL",HERS,M,NaN,NaN,261216,NaN,10011394,CENTELSA,NaN,2016-04-27,2022-10-03
8,71000000182,91000000009,"CABLE ASSEMBLY, POWER, ELECTRICAL",HERS,M,NaN,NaN,261216,NaN,2004008S,CENTELSA,NaN,2016-04-27,2022-10-03
9,71000000182,91000252928,"CABLE ASSEMBLY, POWER, ELECTRICAL",HERS,M,NaN,NaN,261216,NaN,C THHN/THWN 90°C CU 4 AWG 600,CENTELSA,NaN,2016-04-27,2022-10-03

<font color="yellow" size = "4" face = "small fonts">5. Leer un archivo.JSON que contenga data e imprimirlo desde el modulo /data</font></center><br>

In [5]:
#Utilizar las buenas practicas de python
json_path = os.path.join(os.getcwd(),"..", "data", "countries.json")


with open(json_path, mode="r") as file:
    data = json.load(file)

json_data = pd.json_normalize(data)
json_data.head(12)

,capital,name.common,name.official,name.nativeName.bwg.official,name.nativeName.bwg.common,name.nativeName.eng.official,name.nativeName.eng.common,name.nativeName.kck.official,name.nativeName.kck.common,name.nativeName.khi.official,...,name.nativeName.bos.official,name.nativeName.bos.common,currencies.BAM.name,currencies.BAM.symbol,currencies.SSP.name,currencies.SSP.symbol,name.nativeName.pov.official,name.nativeName.pov.common,currencies.LBP.name,currencies.LBP.symbol
0,[Harare],Zimbabwe,Republic of Zimbabwe,Republic of Zimbabwe,Zimbabwe,Republic of Zimbabwe,Zimbabwe,Republic of Zimbabwe,Zimbabwe,Republic of Zimbabwe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[South Tarawa],Kiribati,Independent and Sovereign Republic of Kiribati,NaN,NaN,Independent and Sovereign Republic of Kiribati,Kiribati,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[Accra],Ghana,Republic of Ghana,NaN,NaN,Republic of Ghana,Ghana,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[Pyongyang],North Korea,Democratic People's Republic of Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[Madrid],Spain,Kingdom of Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,[Amman],Jordan,Hashemite Kingdom of Jordan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,[City of San Marino],San Marino,Republic of San Marino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,[Yamoussoukro],Ivory Coast,Republic of Côte d'Ivoire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,[Brasília],Brazil,Federative Republic of Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,[Bogotá],Colombia,Republic of Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,[],Heard Island and McDonald Islands,Heard Island and McDonald Islands,NaN,NaN,Heard Island and McDonald Islands,Heard Island and McDonald Islands,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,[Roseau],Dominica,Commonwealth of Dominica,NaN,NaN,Commonwealth of Dominica,Dominica,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<font color="yellow" size = "4" face = "small fonts">6. Leer un archivo desde una URL de extensión CSV e imprimirlo</font></center><br>

In [6]:
#Utilizar las buenas practicas de python
csv_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

web_csv = pd.read_csv(csv_url)
web_csv.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

<font color="yellow" size = "4" face = "small fonts">7. Para almacenar datos manualmente en una tabla, cree un DataFrame. Al utilizar un diccionario Python de listas, las claves del diccionario se utilizarán como cabeceras de columna y los valores de cada lista como columnas del DataFrame.

Un DataFrame es una estructura de datos bidimensional que puede almacenar datos de diferentes tipos (incluyendo caracteres, enteros, valores de coma flotante, datos categóricos y más) en columnas. Es similar a una hoja de cálculo, una tabla SQL o el data.frame en R.

Cree una tabla que tiene 3 columnas, cada una de ellas con una etiqueta. Las etiquetas de las columnas son respectivamente Nombre, Edad y Sexo.

La columna Nombre consiste en datos textuales con cada valor una cadena, la columna Edad son números y la columna Sexo son datos textuales.</font></center><br>

In [7]:
#Utilizar las buenas practicas de python
people = {
    "Nombre":["Juan","María"],
    "Edad":[21,22],
    "Sexo":["M","F"]      
}

people_data_frame = pd.DataFrame(data=people)
people_data_frame

  Nombre  Edad Sexo
0   Juan    21    M
1  María    22    F

<font color="yellow" size = "4" face = "small fonts">8. Solo interesa trabajar con los datos de la columna Edad, Imprima los datos de esta columna</font></center><br>
<font color="yellow" size = "4" face = "small fonts"> -  - Imprima los datos de esta columna</font></center><br>

In [8]:
for i in people_data_frame.values:
    print(i[1])

21
22

<font color="yellow" size = "4" face = "small fonts">9. Consulte que otro tipo de archivo se pueden cargar en pandas y carguelo e imprimalo-</font></center><br>

In [9]:
xml_url = "https://podcasts.files.bbci.co.uk/p02nq0gn.rss"
response = requests.get(xml_url,headers)
xml_data = pd.read_xml(io.StringIO(response.text),xpath=".//item")
xml_data.head(10)

,title,description,subtitle,summary,image,pubDate,duration,enclosure,enclosureLegacy,enclosureSecure,guid,link,explicit,content,author,canonical
0,Iran attacks energy facilities in the Gulf,<p>Qatar's state-owned petroleum company says ...,"Trump threatens to ""blow up"" Iran's main gas f...",<p>Qatar's state-owned petroleum company says ...,NaN,"Thu, 19 Mar 2026 05:34:00 +0000",1641,NaN,NaN,NaN,urn:bbc:podcast:p0n7gwsq,http://www.bbc.co.uk/programmes/p0n7gwsq,clean,NaN,BBC World Service,/programmes/p0n7gwsq
1,Israel's third top-level assassination in two ...,<p>Iran's Intelligence Minister Esmail Khatib ...,Iran condemns 'cowardly assassination' of its ...,<p>Iran's Intelligence Minister Esmail Khatib ...,NaN,"Wed, 18 Mar 2026 16:28:00 +0000",1685,NaN,NaN,NaN,urn:bbc:podcast:p0n7cx19,http://www.bbc.co.uk/programmes/p0n7cx19,clean,NaN,BBC World Service,/programmes/p0n7cx19
2,Deadly Israeli strikes hit central Beirut,<p>Israel has launched a series of deadly stri...,Lebanon says at least six killed in Israeli at...,<p>Israel has launched a series of deadly stri...,NaN,"Wed, 18 Mar 2026 05:28:00 +0000",1690,NaN,NaN,NaN,urn:bbc:podcast:p0n77nj0,http://www.bbc.co.uk/programmes/p0n77nj0,clean,NaN,BBC World Service,/programmes/p0n77nj0
3,Israel says it's killed Iran's top security chief,<p>Israel's foreign minister said Iranians wer...,Israel's foreign minister says Iranians are 's...,<p>Israel's foreign minister said Iranians wer...,NaN,"Tue, 17 Mar 2026 16:59:00 +0000",1671,NaN,NaN,NaN,urn:bbc:podcast:p0n75gry,http://www.bbc.co.uk/programmes/p0n75gry,clean,NaN,BBC World Service,/programmes/p0n75gry
4,US allies reject Trump's call for help in Stra...,<p>The US President has repeated his call for ...,Donald Trump is met with resistance after call...,<p>The US President has repeated his call for ...,NaN,"Tue, 17 Mar 2026 05:38:00 +0000",1738,NaN,NaN,NaN,urn:bbc:podcast:p0n71mlm,http://www.bbc.co.uk/programmes/p0n71mlm,clean,NaN,BBC World Service,/programmes/p0n71mlm
5,Germany and UK tell Trump this is 'not Nato's ...,<p>Germany and Britain say the war against Ira...,The US president had called on allies to help ...,<p>Germany and Britain say the war against Ira...,NaN,"Mon, 16 Mar 2026 16:28:00 +0000",1736,NaN,NaN,NaN,urn:bbc:podcast:p0n6zd4b,http://www.bbc.co.uk/programmes/p0n6zd4b,clean,NaN,BBC World Service,/programmes/p0n6zd4b
6,The big winners at the Oscars,<p>One Battle After Another wins best picture ...,One Battle After Another wins best picture at ...,<p>One Battle After Another wins best picture ...,NaN,"Mon, 16 Mar 2026 05:44:00 +0000",1918,NaN,NaN,NaN,urn:bbc:podcast:p0n6vy9q,http://www.bbc.co.uk/programmes/p0n6vy9q,clean,NaN,BBC World Service,/programmes/p0n6vy9q
7,Attacks continue after Trump says Iran deal no...,<p>After President Trump said Iran seemed read...,Iran carries out further missile and drone str...,<p>After President Trump said Iran seemed read...,NaN,"Sun, 15 Mar 2026 14:06:00 +0000",795,NaN,NaN,NaN,urn:bbc:podcast:p0n6t1ss,http://www.bbc.co.uk/programmes/p0n6t1ss,clean,NaN,BBC World Service,/programmes/p0n6t1ss
8,Trump urges nations to secure Strait of Hormuz,<p>President Trump calls on other nations to s...,"After Iranian attacks in key shipping lane, US...",<p>President Trump calls on other nations to s...,NaN,"Sun, 15 Mar 2026 04:26:00 +0000",1527,NaN,NaN,NaN,urn:bbc:podcast:p0n6r0lp,http://www.bbc.co.uk/programmes/p0n6r0lp,clean,NaN,BBC World Service,/programmes/p0n6r0lp
9,The Happy Pod: Turning my toddler's tales into...,<p>Stephen Spencer has set his daughter's stor...,Millions of people have watched Stephen Spence...,<p>Stephen Spencer has set his daughter's stor...,NaN,"Sat, 14 Mar 2026 20:00:00 +0000",1659,NaN,NaN,NaN,urn:bbc:podcast:p0n6knf4,http://www.bbc.co.uk/programmes/p0n6knf4,clean,NaN,BBC World Service,/programmes/p0n6knf4

<font color="yellow" size = "4" face = "small fonts">10. Consulte que otro tipo de archivo se pueden cargar en pandas y carguelo e imprimalo-</font></center><br>

In [10]:
# leer tablas cuando se copia o pega la tabla, jajaja me funcionó con la tabla en está pagina, copia y pega la tabla y corre esto https://en.wikipedia.org/wiki/Demographics_of_Colombia

clip_board = pd.read_clipboard()
clip_board.head(10)

Empty DataFrame
Columns: [openpyxl]
Index: []

<font color="red" size = "4" face = "small fonts">-------------------------------------------------------------------------------</font></center><br>

<font color="red" size = "4" face = "small fonts">Calificación del siguinte bloque 2/5</font></center><br>

<center><img src= '..//data/imageProject.png' width='200' height='400'></center>

<font color="yellow" size = "4" face = "small fonts">1. Integrar los datos de los archivos de Excel y generar un archivo temporal.csv que se almacene en el paquete \data\ Lo anterior se debe generar mediante una función escrita en Python y almacenada en la módulo functions y en un archivo.py, ejemplo /functions/myfunctions.py</font></center><br>

<font color="Orange" size = "4" face = "small fonts">Calificación 0,5 de 2 </font></center><br>

In [11]:
#Code
every_excel = os.path.join(os.getcwd(),".." ,"data")

print(unir_excel_en_csv(every_excel))

Todo unido a csv yay jejej

<font color="yellow" size = "4" face = "small fonts">2. Con el archivo temporal.csv se debe realizar la siguiente transformación, recordar que todo se debe realizar con funciones escritas en un archivo.py guardado en la carpeta \functions e invocadas en archivo parcialBDM.ipynb</font></center><br>

<font color="yellow" size = "4" face = "small fonts">*   Cambiar los encabezados por: stock, material, descripcion, tipoMaterial, umb, mat, sm, grupo, jerarquia, numerofab, fabricante, extension, creado, modificado</font></center><br>

<font color="yellow" size = "4" face = "small fonts">*   Eliminar las columnas que no tengan ningun dato y eliminar todos los registros que no tengan fecha en la columna modificado.</font></center><br>

<font color="Orange" size = "4" face = "small fonts">Calificación 0,5 de 2 </font></center><br>

In [12]:
#Code
new_columns = ["stock","material","descripcion","tipoMaterial","umb","mat","sm","grupo","jerarquia","numerofab","fabricante","extension","creado","modificado"]
data_path = os.path.join(os.getcwd(), ".." , "data")

print(alterar_columnas(data_path,new_columns))

/home/juancho/Documents/pandas_stuff/TallerPythonPandas/functions/misfunciones.py:30: DtypeWarning: Columns (0: Mat.gestion.stock) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(new_data_path)

Columnas alteradas yay jeje

<font color="orange" size = "4" face = "small fonts">Tenga en cuenta que las Bases de Datos se encuentran en el contenedor del Docker (Taller anterior)</font></center><br>

### Escribir el script en este Markdown de creación e inicio de la BD.

```docker
docker run -dit --name tallerbd -p 9090:3306 -e MYSQL_ROOT_PASSWORD=root mysql:latest 
docker exec -it tallerbd mysql -u root -p
password:root

```

``` SQL
create database parcialDB;
use parcialDB;

CREATE TABLE producto(
    material VARCHAR(255),
    descripcion VARCHAR(255),
    fabricante VARCHAR(255),
    modificado DATE 
);
```

<font color="yellow" size = "4" face = "small fonts">3. Importar el archivo data.csv a una tabla producto de una Bases de Datos mariaDB. Todas las sentencias se deben realizar desde este cuaderno y con funciones.</font></center><br>

<font color="yellow" size = "4" face = "small fonts">* Crear la Bases de Datos con el nombre parcialDB y una tabla de nombre "producto" con las columnas material, descripcion, fabricante y modificado.</font></center><br>

<font color="yellow" size = "4" face = "small fonts">* Cargar los datos desde temporal.csv a la tabla "material"</font></center><br>


<font color="Orange" size = "4" face = "small fonts">Calificación 0,5 de 2 </font></center><br>

In [13]:
#Code

conn = establecer_conexion()
print(cargar_datos(conn))

NameError: name 'cargar_datos' is not defined


<font color="yellow" size = "4" face = "small fonts">4. Generar graficas desde los datos contenidos en la base de datos parcialDB, tabla producto. </font></center><br>
<font color="Orange" size = "4" face = "small fonts">Calificación 0,5 de 2 </font></center><br>

<font color="red" size = "4" face = "small fonts">-------------------------------------------------------------------------------</font></center><br>

<font color="red" size = "4" face = "small fonts">Calificación del siguinte bloque 2/5</font></center><br>

<font color="yellow" size = "4" face = "small fonts">1. Crear y cargar la base de datos de recursos humanos dentro del contenedor Docker, recuerde se debe realizar todas las sentencias y programación necesaria desde este cuaderno. </font></center><br>
<font color="Orange" size = "4" face = "small fonts">Calificación 1 de 2 </font></center><br>

<font color="yellow" size = "4" face = "small fonts">2. Generar la siguinte consulta de la base de datos - recursos humanos.  </font></center><br>
<font color="yellow" size = "4" face = "small fonts">- -Se desea conocer los empleados cuyo salario es superior al salario promedio de todos los empleados. </font></center><br>
<font color="Orange" size = "4" face = "small fonts">Calificación 0,5 de 2 </font></center><br>

<center><font color="red" size = "4" face = "small fonts">CUANDO TERMINE EL PRÁCTICO CREE UN ARCHIVO.ZIP DE LA CARPETA DEL PROYECTO Y CÁRGUELO AL AULA VIRTUAL.</font></center>